apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: houba
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/trivoallan/houba
    targetRevision: main
    path: deploy/argocd/sources/houba-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: houba
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
