apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: platform-dev
  namespace: houba
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: platform
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        - uses: compose-output
          config:
            output: dev
