"""Scan-queue port. The adapter (RedisStreamsAdapter) holds the broker connection;
this Protocol is broker-agnostic — the stream id is wrapped in Reservation.token,
never surfaced as a Redis-specific value. See ADR 0043."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol


@dataclass(frozen=True)
class Reservation:
    token: str  # opaque, adapter-private (a Redis Streams message id today)
    ref: str  # host/repo@sha256:...


class QueuePort(Protocol):
    def enqueue(self, refs: list[str]) -> None: ...
    def reserve(self) -> Reservation | None: ...
    def ack(self, res: Reservation, *, digest: str, attested_at: str) -> None: ...
    def dead_letter(self, res: Reservation, *, ref: str, reason: dict[str, str]) -> None: ...
    def reaper(self, *, min_idle_ms: int, max_deliveries: int) -> list[str]: ...
    def coverage_check(self, placed: list[str], *, max_age_s: int, now: float) -> list[str]: ...
    def dlq_list(self) -> list[dict[str, str]]: ...
    def dlq_replay(self, selector: str) -> int: ...
    def dlq_drop(self, selector: str) -> int: ...
