import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// One autogenerated sidebar mirroring the Diátaxis folder structure under docs/.
const sidebars: SidebarsConfig = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
